name: pokejisho_core
description: A Dart core for PokéJisho projects.
version: 0.0.1
homepage: https://michaelcharl.es/aubrey

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
